import type { ToolContent } from '../toolContentTypes';
import { activationContent } from './activation';
import { adminNoticeContent } from './admin-notice';
import { blockPatternContent } from './block-pattern';
import { childThemeContent } from './child-theme';
import { colorContent } from './color';
import { commentQueryContent } from './comment-query';
import { cronContent } from './cron';
import { dashboardWidgetContent } from './dashboard-widget';
import { dateQueryContent } from './date-query';
import { defaultHeadersContent } from './default-headers';
import { enqueueContent } from './enqueue';
import { hooksContent } from './hooks';
import { listTableContent } from './list-table';
import { metaBoxContent } from './meta-box';
import { metaQueryContent } from './meta-query';
import { navMenuContent } from './nav-menu';
import { oembedContent } from './oembed';
import { pluginHeaderContent } from './plugin-header';
import { postMetaContent } from './post-meta';
import { postStatusContent } from './post-status';
import { postTypeContent } from './post-type';
import { quicktagsContent } from './quicktags';
import { readmeContent } from './readme';
import { restRouteContent } from './rest-route';
import { settingsPageContent } from './settings-page';
import { shortcodeContent } from './shortcode';
import { sidebarContent } from './sidebar';
import { taxQueryContent } from './tax-query';
import { taxonomyContent } from './taxonomy';
import { termMetaContent } from './term-meta';
import { termQueryContent } from './term-query';
import { themeJsonContent } from './theme-json';
import { themeSupportContent } from './theme-support';
import { toolbarContent } from './toolbar';
import { userContactContent } from './user-contact';
import { userQueryContent } from './user-query';
import { userRoleContent } from './user-role';
import { wcAccountEndpointContent } from './wc-account-endpoint';
import { wcCartFeeContent } from './wc-cart-fee';
import { wcCheckoutFieldsContent } from './wc-checkout-fields';
import { wcEmailContent } from './wc-email';
import { wcOrderQueryContent } from './wc-order-query';
import { wcOrderStatusContent } from './wc-order-status';
import { wcPaymentGatewayContent } from './wc-payment-gateway';
import { wcProductFieldsContent } from './wc-product-fields';
import { wcProductTabsContent } from './wc-product-tabs';
import { wcShippingMethodContent } from './wc-shipping-method';
import { widgetContent } from './widget';
import { wpConfigContent } from './wp-config';
import { wpQueryContent } from './wp-query';

/**
 * Long-form content per tool id. GENERATED by `npm run content-index` from the
 * one-file-per-tool sources in this directory — edit those, not this file.
 *
 * Every tool in `src/data/tools.ts` must have an entry; the generator script
 * fails if one is missing, because a tool page without its content section has
 * almost no indexable prose.
 */
export const TOOL_CONTENT: Record<string, ToolContent> = {
  'activation': activationContent,
  'admin-notice': adminNoticeContent,
  'block-pattern': blockPatternContent,
  'child-theme': childThemeContent,
  'color': colorContent,
  'comment-query': commentQueryContent,
  'cron': cronContent,
  'dashboard-widget': dashboardWidgetContent,
  'date-query': dateQueryContent,
  'default-headers': defaultHeadersContent,
  'enqueue': enqueueContent,
  'hooks': hooksContent,
  'list-table': listTableContent,
  'meta-box': metaBoxContent,
  'meta-query': metaQueryContent,
  'nav-menu': navMenuContent,
  'oembed': oembedContent,
  'plugin-header': pluginHeaderContent,
  'post-meta': postMetaContent,
  'post-status': postStatusContent,
  'post-type': postTypeContent,
  'quicktags': quicktagsContent,
  'readme': readmeContent,
  'rest-route': restRouteContent,
  'settings-page': settingsPageContent,
  'shortcode': shortcodeContent,
  'sidebar': sidebarContent,
  'tax-query': taxQueryContent,
  'taxonomy': taxonomyContent,
  'term-meta': termMetaContent,
  'term-query': termQueryContent,
  'theme-json': themeJsonContent,
  'theme-support': themeSupportContent,
  'toolbar': toolbarContent,
  'user-contact': userContactContent,
  'user-query': userQueryContent,
  'user-role': userRoleContent,
  'wc-account-endpoint': wcAccountEndpointContent,
  'wc-cart-fee': wcCartFeeContent,
  'wc-checkout-fields': wcCheckoutFieldsContent,
  'wc-email': wcEmailContent,
  'wc-order-query': wcOrderQueryContent,
  'wc-order-status': wcOrderStatusContent,
  'wc-payment-gateway': wcPaymentGatewayContent,
  'wc-product-fields': wcProductFieldsContent,
  'wc-product-tabs': wcProductTabsContent,
  'wc-shipping-method': wcShippingMethodContent,
  'widget': widgetContent,
  'wp-config': wpConfigContent,
  'wp-query': wpQueryContent,
};

export function getToolContent(id: string): ToolContent | null {
  return TOOL_CONTENT[id] ?? null;
}
